//
//  Events.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Events: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _class: String?
    var _id: String?
    var _date: String?
    var _description: String?
    var _location: String?
    var _maxNum: NSNumber?
    var _participants: [String]?
    var _time: String?
    
    class func dynamoDBTableName() -> String {

        return "studybuddy-mobilehub-771666090-Events"
    }
    
    class func hashKeyAttribute() -> String {

        return "_class"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_id"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_class" : "class",
               "_id" : "id",
               "_date" : "date",
               "_description" : "description",
               "_location" : "location",
               "_maxNum" : "maxNum",
               "_participants" : "participants",
               "_time" : "time",
        ]
    }
}
