//
//  UserList.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class UserList: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _events: [String]?
    var _prefName: String?
    
    class func dynamoDBTableName() -> String {

        return "studybuddy-mobilehub-771666090-UserList"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_events" : "events",
               "_prefName" : "prefName",
        ]
    }
}
